### ISSUE TITLE
Maintain selections on update

### ISSUE THREAD

**Issue by reichd** [NPSCORELAB/harrypotterexplorer#1]
Currently, when the level of strength in modified, any selection from the dropdown list is reset. It would be good to maintain selections on update, aside from the one being modified to trigger the update.

**Comment by cjcallag** [comment]
Hi Daniel,

I just want to ensure that

**Comment by cllghn** [comment]
The requested functionality can be achieved by including `visNetworkProxy` to the current visualizations setup:

https://datastorm-open.github.io/visNetwork/shiny.html

**Comment by rschroedy** [comment]
New version should now stay selected as a node on the graph.
